name: Build and Upload

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install and Build
        run: |
          yarn install --frozen-lockfile
          yarn build

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: './build'
